name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run audit and fix
        run: |
          npm audit fix
          npm audit --audit-level=moderate || true
      - name: Build project
        run: |
          cd backend
          npm install
          npm audit fix
          npm audit --audit-level=moderate || true
          npm run build
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm audit fix
          npm audit --audit-level=moderate || true
          npm run build 